### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by bheni** [shahinrostami/pokemon_dataset#1]
I'm curious where the pokemon_gen_1_to_8.csv dataset came from, and was wondering if you would add a license file to this repository?  I would like to put a mirror of this data up on dolthub.com.

**Comment by shahinrostami** [comment]
Hello @bheni . The current trace of the dataset is in the README.md > changelog. The original is here (https://www.kaggle.com/tlegrand/pokemon-with-stats-generation-8). I've just set a license (the same as the original), if you have a better suggestion please let me know! I've never heard of dolthub.com, thank you for sharing.

**Comment by bheni** [comment]
The data is up https://www.dolthub.com/repositories/Liquidata/pokemon if you are curious

**Comment by shahinrostami** [comment]
> The data is up https://www.dolthub.com/repositories/Liquidata/pokemon if you are curious

Great stuff!
